### PR TITLE
Added more parts with stack hatches.

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Just tossed another couple of parts on the pile.

**Comment by PapaJoesSoup** [comment]
thanks.   I'll be addressing these and the updated interface in a few days.   I've got SM almost ready for release.  CLS and RM are next

**Comment by Kerbas-ad-astra** [comment]
Resolved conflict (since the Mk1 crew cabin was added by #65).

**Comment by Technologicat** [comment]
Sorry about the conflict! I completely missed this pull request when preparing #65.

**Comment by PapaJoesSoup** [comment]
Merged.  Thanks both of you!

**Pull request merged**
