### PR TITLE
Yes/No problem in right-click menu in the VAB and Russian localization

### PR DESCRIPTION
**Pull request by yalov**
Bug report from [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/109972-130-connected-living-space-v1253-1-jun-2017-localization/&do=findComment&comment=3095991):
> In the right-click menu in the VAB (at the very least), for 'CLS Passable' 'No' means it's passable, and 'Yes' means it isn't passable.
> Took me a while to figure out what was going on there.

 I fixed that at localization file and added beta for russian, but it isn't work for  "Connected Living Space" info-block for parts at VAB. [printscreen](https://user-images.githubusercontent.com/12796450/30833997-e5362656-a259-11e7-840e-eac0970c9e01.png

It's same for "Docking Hatch" info-block. And "Docking Hatch" string absents at .cfg.

### CODE REVIEW

**Comment by yalov** [comment]
@linuxgurugamer, 
I have seen these changes at your commit history but not in the release. Has it intended ?

**Comment by linuxgurugamer** [comment]
It's currently an unofficial release.  When @codepoetpbowden comes back, I'll be pushing them to him

**Comment by yalov** [comment]
@codepoetpbowden what about last commit there?

**Comment by linuxgurugamer** [comment]
All of those were incorporated into my version, and it was pulled back into the master when he came back.  If you made a commit after I did the merge, then it probably isn't included

**Comment by yalov** [comment]
ok, then I will open a new one

**Pull request closed without merging**
